apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/urmilagulaskar/devops-poc.git
    targetRevision: HEAD
    path: my-app-deployment-master/example-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: example-app
  syncPolicy:
    automated:
      prune: false
      selfHeal: false